apiVersion: v1
kind: Service
metadata:
  name: rent-app-service
  labels:
    app: rent-app 
spec:
  selector:
    app: rent-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
